snps_accel_app: Fix of_dma_configure() build issue for kernel v6.12
Fix a compilation failure when building the driver against kernel
v6.12 and later:

  error: implicit declaration of function 'of_dma_configure'

Kernel v6.12 refactored the DMA configuration API. The
of_dma_configure() helper is no longer available to drivers, and
DMA configuration must instead be performed through
of_dma_configure_id(), which accepts an additional ID lookup index
parameter.

Signed-off-by: Pavel Kozlov <pavel.kozlov@globalfoundries.com>